branch-defaults:
  main:
    environment: paas-backend-prod
    group_suffix: null

global:
  application_name: paas-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application

deploy:
  artifact: Dockerrun.aws.json

environment-defaults:
  paas-backend-prod:
    branch: null
    repository: null

environment:
  name: paas-backend-prod
  solution-stack-name: "64bit Amazon Linux 2 v3.7.1 running Docker"